apiVersion: v1
kind: Service
metadata:
  name: devcalc-service
  labels:
    app: devcalc
spec:
  type: NodePort
  selector:
    app: devcalc
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
    nodePort: 30007
    name: http
  sessionAffinity: None
